on:
  pull_request:
  push:
    branches: [master]
name: nix
jobs:
  haddock:
    runs-on: ubuntu-latest
    name: Nix build
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build and generate haddock
        run: nix build
      
      - name: Deploy generated haddock to github pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result-doc/share/doc/arch-web-*/html
